// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface IERC20 {
    function transfer(address to, uint256 amount) external returns (bool);
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
}

/// @title MeridianVault
/// @author Meridian Finance Team
/// @notice ERC4626-compliant tokenized yield vault
/// @dev Accepts an underlying asset and mints proportional shares.
///      Yield is generated by deploying assets into lending and LP strategies.
contract MeridianVault {
    IERC20 public immutable asset;

    string public name;
    string public symbol;
    uint8 public constant decimals = 18;

    uint256 public totalSupply;
    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
    event Deposit(address indexed caller, address indexed owner, uint256 assets, uint256 shares);
    event Withdraw(
        address indexed caller,
        address indexed receiver,
        address indexed owner,
        uint256 assets,
        uint256 shares
    );

    error ZeroShares();
    error ZeroAssets();
    error InsufficientShares();
    error AllowanceExceeded();

    constructor(address _asset, string memory _name, string memory _symbol) {
        require(_asset != address(0), "Invalid asset");
        asset = IERC20(_asset);
        name = _name;
        symbol = _symbol;
    }

    // ═══════════════════════════════════════════════════════════════════════
    // ERC4626 — ACCOUNTING
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice Total assets under management
    function totalAssets() public view returns (uint256) {
        return asset.balanceOf(address(this));
    }

    /// @notice Convert an asset amount to shares
    function convertToShares(uint256 assets) public view returns (uint256) {
        uint256 supply = totalSupply;
        if (supply == 0) {
            return assets;
        }
        return (assets * supply) / totalAssets();
    }

    /// @notice Convert shares to their underlying asset value
    function convertToAssets(uint256 shares) public view returns (uint256) {
        uint256 supply = totalSupply;
        if (supply == 0) {
            return shares;
        }
        return (shares * totalAssets()) / supply;
    }

    // ═══════════════════════════════════════════════════════════════════════
    // ERC4626 — DEPOSIT / WITHDRAW
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice Deposit assets and receive vault shares
    /// @param assets Amount of underlying asset to deposit
    /// @param receiver Address to receive the minted shares
    function deposit(uint256 assets, address receiver) external returns (uint256 shares) {
        shares = convertToShares(assets);
        if (shares == 0) revert ZeroShares();

        asset.transferFrom(msg.sender, address(this), assets);

        totalSupply += shares;
        balanceOf[receiver] += shares;

        emit Transfer(address(0), receiver, shares);
        emit Deposit(msg.sender, receiver, assets, shares);
    }

    /// @notice Withdraw exact assets by burning proportional shares
    function withdraw(
        uint256 assets,
        address receiver,
        address owner
    ) external returns (uint256 shares) {
        shares = convertToShares(assets);
        _spendAllowance(owner, msg.sender, shares);

        if (balanceOf[owner] < shares) revert InsufficientShares();

        balanceOf[owner] -= shares;
        totalSupply -= shares;

        asset.transfer(receiver, assets);

        emit Transfer(owner, address(0), shares);
        emit Withdraw(msg.sender, receiver, owner, assets, shares);
    }

    /// @notice Redeem shares for underlying assets
    function redeem(
        uint256 shares,
        address receiver,
        address owner
    ) external returns (uint256 assets) {
        _spendAllowance(owner, msg.sender, shares);
        if (balanceOf[owner] < shares) revert InsufficientShares();

        assets = convertToAssets(shares);
        if (assets == 0) revert ZeroAssets();

        balanceOf[owner] -= shares;
        totalSupply -= shares;

        asset.transfer(receiver, assets);

        emit Transfer(owner, address(0), shares);
        emit Withdraw(msg.sender, receiver, owner, assets, shares);
    }

    // ═══════════════════════════════════════════════════════════════════════
    // ERC20 — SHARE TOKEN
    // ═══════════════════════════════════════════════════════════════════════

    function approve(address spender, uint256 amount) external returns (bool) {
        allowance[msg.sender][spender] = amount;
        emit Approval(msg.sender, spender, amount);
        return true;
    }

    function transfer(address to, uint256 amount) external returns (bool) {
        if (balanceOf[msg.sender] < amount) revert InsufficientShares();
        balanceOf[msg.sender] -= amount;
        balanceOf[to] += amount;
        emit Transfer(msg.sender, to, amount);
        return true;
    }

    function transferFrom(address from, address to, uint256 amount) external returns (bool) {
        _spendAllowance(from, msg.sender, amount);
        if (balanceOf[from] < amount) revert InsufficientShares();
        balanceOf[from] -= amount;
        balanceOf[to] += amount;
        emit Transfer(from, to, amount);
        return true;
    }

    function _spendAllowance(address owner, address spender, uint256 amount) internal {
        if (spender == owner) return;
        uint256 allowed = allowance[owner][spender];
        if (allowed != type(uint256).max) {
            if (allowed < amount) revert AllowanceExceeded();
            allowance[owner][spender] = allowed - amount;
        }
    }
}
